// Shared domain types used across the application.
// Database entity types are generated by Prisma — import them from
// `@prisma/client`.  This file holds application-level types that are
// not tied to a single layer.
