// Shared domain types used across the application.
// Database entity types are generated by Prisma — import them from
// `@prisma/client`.  This file holds application-level types that are
// not tied to a single layer.

// `export {}` makes this a TypeScript module so `declare global` below is
// treated as a proper module-level global augmentation.
export {}

// ---------------------------------------------------------------------------
// GA4 / gtag.js globals
// ---------------------------------------------------------------------------
// These properties are injected by the beforeInteractive inline script in the
// root layout and consumed by ConsentContext when updating Consent Mode v2.

declare global {
  interface Window {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    gtag: (...args: any[]) => void
    dataLayer: unknown[]
  }
}
